### ISSUE TITLE
Debian status command not found

### ISSUE THREAD

**Issue by tobemedia** [appserver-io/appserver#585] opened 2015-02-22 13:18 UTC
on a fresh Debian 7.8.0 install a 

/etc/init.d/appserver-watcher status causes this output / error:
Status of Appserver Watcher aka Deployment Scanner: /etc/init.d/appserver-watcher: line 58: status: command not found

and

/etc/init.d/appserver status
Status of appserver: /etc/init.d/appserver: line 66: status: command not found

**Comment by waja** [comment] 2015-02-22 18:24
On https://wiki.debian.org/LSBInitScripts/StatusSupport you can find the following:

"Every init script [...] in Debian [...] should support the "status" action in an LSB-conforming and meaningful way."

So this is a recommended feature but not a bug.

**Comment by waja** [comment] 2015-02-22 19:33
Opened new isse  at https://github.com/appserver-io-dist/debian/issues/33, please close it.

**Comment by tobemedia** [comment] 2015-02-22 20:56
What? You answer it's a Feature not a bug and at the Same Time you open a new issue with the underlaying problem?

**Closed** 2015-02-22 20:58 UTC

**Comment by waja** [comment] 2015-02-22 21:04
This is indeed an issue. A status command is usefull. But it's not a bug, but a wishlist issue.

Anyways ... I've learned you should reopen the issue at https://github.com/appserver-io-dist/debian

**Comment by tobemedia** [comment] 2015-02-22 21:17
Reopened at https://github.com/appserver-io-dist/debian/issues/35
