### ISSUE TITLE
[appserver-io/appserver] Replace all FS functions with flysystem Library

### ISSUE THREAD

**Issue by wagnert** [appserver-io/appserver#691] opened 2015-03-17 08:42 UTC
All functions to that access FS has to be replaced with a integration of [flysystem](https://github.com/thephpleague/flysystem) library and a VFS. This should make writing of PHPUnit tests simpler and enables appserver.io to support virtual filesystems.

**Comment by smolinari** [comment] 2015-11-10 16:42
:+1: 

Looking forward to this, as we are planning to use Rackspace Cloud Files in our system at some point, but at first will be using a standard file system. The flysystem FS abstraction will make the change painless. 

Scott

**Comment by wick-ed** [comment] 2015-11-24 10:07
Closed as being a duplicate of #626

**Closed by wick-ed** 2015-11-24 10:07 UTC
Labels: enhancement
